# Generated by Django 5.2.7 on 2025-10-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='cname',
            new_name='name',
        ),
    ]
